[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

[[inputs.socket_listener]]
  service_address = "tcp://:2003"
  data_format = "graphite"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "gatling-admin-token"
  organization = "performance-org"
  bucket = "gatling-metrics"
