reporting-disabled = false

[[graphite]]
  enabled = true
  bind-address = ":2003"
  database = "gatling-metrics"
  retention-policy = "autogen"
  protocol = "tcp"
  consistency-level = "one"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  separator = "."
  tags = []
